# Generated by Django 4.2 on 2023-07-01 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betcodes', '0005_comment_parentid_comment_updated_at_likes_parentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parentId',
            new_name='parent_id',
        ),
    ]
