# Generated by Django 4.2 on 2023-07-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcodes', '0007_remove_comment_name_remove_comment_parent_id_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
